-- MySQL compatible schema
CREATE TABLE COURSES (
  COURSE_ID varchar(255) NOT NULL,
  SUBJECT varchar(55) DEFAULT NULL,
  COURSE_NUMBER varchar(55) DEFAULT NULL,
  SECTION varchar(55) DEFAULT NULL,
  ENROLLMENT integer DEFAULT 0,
  COURSE_TYPE varchar(55) DEFAULT NULL,
  PRIMARY KEY (COURSE_ID)
);
