-- This script is only used for loading test sample data (not used for normal runs)
-- Script failures will cause the application to fail to start
-- MySQL compatible schema

-- Add some sample persons
INSERT INTO PERSONAL (ALTERNATIVE_ID,PERCENTILE,SAT_VERBAL,SAT_MATH,ACT_COMPOSITE,AGE,RACE,GENDER,STATUS,EARNED_CREDIT_HOURS,GPA_CUMULATIVE,GPA_SEMESTER,STANDING,PELL_STATUS,CLASS_CODE) VALUES ('AZ_ALT_1',99,600,800,0,40,1,2,1,186,3.1,4,1,1,'SR');
INSERT INTO PERSONAL (ALTERNATIVE_ID,PERCENTILE,SAT_VERBAL,SAT_MATH,ACT_COMPOSITE,AGE,RACE,GENDER,STATUS,EARNED_CREDIT_HOURS,GPA_CUMULATIVE,GPA_SEMESTER,STANDING,PELL_STATUS,CLASS_CODE) VALUES ('BZ_ALT_1',99,710,800,0,35,1,1,1,150,3.9,4,2,1,'GR');

-- Add some sample courses
INSERT INTO COURSE (COURSE_ID,SUBJECT,ENROLLMENT,ONLINE_FLAG) VALUES ('MATH_101_10101_201401', 'MATH', 2, 0);
INSERT INTO COURSE (COURSE_ID,SUBJECT,ENROLLMENT,ONLINE_FLAG) VALUES ('MATH_201_2222_201401', 'MATH', 0, 0);
INSERT INTO COURSE (COURSE_ID,SUBJECT,ENROLLMENT,ONLINE_FLAG) VALUES ('MATH_110_1234_201401', 'MATH', 0, 1);

-- And then a couple enrollments
