-- This script is only used for loading test sample data (not used for normal runs)
-- Script failures will cause the application to fail to start
-- MySQL compatible schema

-- Add some sample persons
INSERT INTO PERSONAL (ALTERNATIVE_ID,PERCENTILE,SAT_VERBAL,SAT_MATH,ACL_COMPOSITE,AGE,RACE,GENDER,STATUS,SEMESTERS,EARNED_CREDIT_HOURS,GPA_CUMULATIVE,GPA_SEMESTER,STANDING,PELL_STATUS) VALUES ('AZ_ALT_1',99,600,800,0,40,1,2,1,17,186,3.1,4,1,1);
INSERT INTO PERSONAL (ALTERNATIVE_ID,PERCENTILE,SAT_VERBAL,SAT_MATH,ACL_COMPOSITE,AGE,RACE,GENDER,STATUS,SEMESTERS,EARNED_CREDIT_HOURS,GPA_CUMULATIVE,GPA_SEMESTER,STANDING,PELL_STATUS) VALUES ('BZ_ALT_1',99,710,800,0,35,1,1,1,10,150,3.9,4,2,1);

-- Add some sample courses
INSERT INTO COURSE (COURSE_ID, SUBJECT, COURSE_NUMBER, SECTION, ENROLLMENT, COURSE_TYPE) VALUES ('MATH_101_10101_201401', 'MATH', '101', '10101', 2, 0);
INSERT INTO COURSE (COURSE_ID, SUBJECT, COURSE_NUMBER, SECTION, ENROLLMENT, COURSE_TYPE) VALUES ('MATH_201_2222_201401', 'MATH', '201', '2222', 0, 0);
INSERT INTO COURSE (COURSE_ID, SUBJECT, COURSE_NUMBER, SECTION, ENROLLMENT, COURSE_TYPE) VALUES ('MATH_110_1234_201401', 'MATH', '110', '1234', 0, 1);

-- And then a couple enrollments
